# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

  global:
      PYTHON: "C:\\conda"
      MINICONDA_VERSION: "latest"
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
      PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                        # of 32 bit and 64 bit builds are needed, move this
                        # to the matrix section.
      # For this package-template, we include examples of Cython modules,
      # so Cython is required for testing. If your package does not include
      # Cython code, you can set CONDA_DEPENDENCIES=''
      #CONDA_DEPENDENCIES: "Cython"
      CONDA_DEPENDENCIES: ""

  matrix:

      # We test Python 3.7 and 3.6 here.

      - PYTHON_VERSION: "2.7"
        ASTROPY_VERSION: "1.3"
        NUMPY_VERSION: "1.12"

      - PYTHON_VERSION: "3.6"
        ASTROPY_VERSION: "2.0"
        NUMPY_VERSION: "1.13"

platform:
    -x64

install:
    - "git clone git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"

# Not a .NET project, we build the package in the install step instead
build: false

test_script:
  - "%CMD_IN_ENV% python setup.py test"
